### ISSUE TITLE
Default the `SkillCard iconName` prop to the `name` prop 💡

### ISSUE THREAD

**Issue by GregSweats** [sarthikg/portfolio#129]
Hey!

Idea for you, take it or not, feel free to close this Issue either way.

How about defaulting the `SkillCard` component's `iconName` to the `title` if not passed? Then you just have to pass in the very rare occasion it's different?

https://github.com/sarthikg/portfolio/blob/af174d12f5ffc0d802ad4cd1ca0956dd8afd3bd8/src/pages/about.astro#L37

## Background

I just stumbled across a GH issue from you, containing a `...vercel.app` link so I figured let's see what's going on.... then I was impressed, lol.

I am working on a Resume and want to use something similar to `SkillCard` (great name btw) and when thinking about it, I thought, why not use the title/name as the default for the icon name...90% of the time it's probably the exact same.

So, maybe you want to do that? I'd fork you but I'll get too distracted and forget....just like I'll likely forget to check/reply to this...so all the best! 

## ✌️😍😋

Mad props and respect bro. Good job with Weather Torrent / Google SoC, the bug on Azure, and even the blog article I have yet to read but will after this on your dev domain about how you like Astro (I'm loving it BTW! 20+ years programming, mainly Backend/DevOps focused, but do the FE stuff for several years now, both with Static Site Generators / Jamstack, and actual client work in React, Vue, Next, TypeScript, etc...

Thank you!

**Comment by GregSweats** [comment]
Forgot to add a link back to the GitHub post I found you on while searching for a built-for-Astro [react-placeholder] type feature for Astro, before just using that package (love Astro).

https://github.com/withastro/astro/issues/9684

**Comment by sarthikg** [comment]
@GregSweats, seems like I somehow missed the github notification of this issue. I just saw it today when I was planning to fix another long pending issue.

First of all, thanks a lot for taking time in reading through the codebase of a random repository on the internet, and kudos for such a great suggestion!

I was not expecting anyone to even come across the gh-issue in the astro repo that I raised since it was such a niche-bug. But, I'm honestly kinda surprised seeing the analytics & discovering how many of the visitors are from github.😅

I think your suggestion is totally valid. I remember when I initially designed the interface for the data, I was expecting that by the time I'll be writing the UI, I'll probably stumble upon some library which includes all the icons for these programming-languages & frameworks. I remember not finding anything, and deciding that i'll have to manually find the svg's for each of them & modify such that they can take the colors I wanted them to look like.

In between all of this, I somehow missed the point that since the name of the icons is now in my control, I could have just used the title. Though, as a current-fix, instead of changing the actual interface of the data, I'm changing the application logic, but will surely incorporate the complete fix in coming few days.

Also, nice interacting with you! Feel free to drop the link to your resume/portfolio as well. I'll be more than happy in taking a look at it, and learning something new!

Thanks a lot once again!
